### ISSUE TITLE
Add info about best practices for color variables

### ISSUE THREAD

**Issue by proand** [folkehelseinstituttet/Fhi.Frontend.Style#27]
The designers are changing the color palette:  #28 
Since we obviously have to deal with constant changes to core design features the system needs to be as robust as possible when it comes to color variables. Here are some best practices to achieve this:

- Create `color aliases` in the library for common use cases
- Create `color aliases` in each project using the library for less generic use cases 
- Limit the use of `color variables` anywhere else than in the definition of color aliases

The result is a system where designers can add/remove colors without impacting other files than `_variables.color-aliases.scss` either in this library or in any given project using the library.

**Comment by yleaxeman** [comment]
@proand - I'll leave this up to you to delete.
