### ISSUE TITLE
Importing default font used for headings

### ISSUE THREAD

**Issue by maqnus** [folkehelseinstituttet/Fhi.Frontend.Style#3]
### Subject of the issue
The font "CrimsonText" is set to be the main serif-font used for headings in Fhi.Frontend.Style. This font does not seem to exist.
This font is not included, and neither do I think it actually exist, currently the fallback-font "Cambria" are used instead.

What do exist are the "Crimson Text" from [Google Fonts](https://fonts.google.com/specimen/Crimson+Text).
This font are licensed under the Open Font License, and should be included in the prosject.

**Comment by proand** [comment]
Jeg er ikke enig i denne...  "CrimsonText" må du legge til selv siden den ikke er open-source. Cambria er ok fallback-font.
@TonyHopland som har lagt "fallback-system", hør med ham hvis det er noe som ikke fungerer som tiltenkt.
