### ISSUE TITLE
Implement Datepicker component

### ISSUE THREAD

**Issue by maqnus** [folkehelseinstituttet/Fhi.Frontend.Style#38]
FHI-styling for https://ng-bootstrap.github.io/#/components/datepicker

**Comment by proand** [comment]
We are going for self contained components in [Fhi.Frontend.NgComponents](https://github.com/folkehelseinstituttet/Fhi.Frontend.NgComponents). See eg. [fhi-accordion.scss](https://github.com/folkehelseinstituttet/Fhi.Frontend.NgComponents/blob/main/projects/ng-components/src/lib/fhi-accordion/fhi-accordion.scss).
