### ISSUE TITLE
Ikonbestilling: "lock"

### ISSUE THREAD

**Issue by proand** [folkehelseinstituttet/Fhi.Frontend.Style#392]
Kopiert fra https://github.com/folkehelseinstituttet/Fhi.Frontend.Demo/issues/633
> Vi trenger denne for å vise at et element ikke kan redigeres:
> https://icons.getbootstrap.com/icons/lock/

**Comment by proand** [comment]
Har denne høy pri @cathral ?

**Comment by cathral** [comment]
> Har denne høy pri @cathral ?

Den er en del av denne US'en: [User Story 97265](https://fhi.visualstudio.com/Team%20D/_workitems/edit/97265): Begrense redigeringsmuligheter for menypunkt fra Ny versjon

Vi tenkte å prøve å få startet på den i neste sprint (uke 35+36), men usikkert om det er realistisk. Ikke kritisk på noen måte.

**Comment by cathral** [comment]
Denne haster ikke - blir sannsynligvis ikke påbegynt nå likevel

**Comment by trybern** [comment]
Ikon er lagt til og kommer med neste release.
