### ISSUE TITLE
Tabell: Støtte for uthevet tekst i kolonneheader

### ISSUE THREAD

**Issue by cathral** [folkehelseinstituttet/Fhi.Frontend.Style#397]
### Description

FHI Statistikk har behov for å sette font-weight bold eller semibold for tekst i kolonneheadere for hele tabellen  slik at det blir lettere for brukerne av løsningen å få et overblikk over hva tabellen inneholder

![image](https://github.com/user-attachments/assets/847838a5-ba21-48a8-b290-057d375a3fcf)

**Comment by trybern** [comment]
Vi har oppdaget flere behov som strekker seg utover det som er lov med dagens Angular-komponent, hvor dette er ett av dem. For eksempel er det ingen "Header Column" på skjermdumpene over. I dag er ikke dette mulig "ut-av-repo-et". Siden vi omdirigerer kruttet til det nye systemet med rammeverksagnostiske komponenter, skal det mye til før vi gjør andre endringer enn feilrettinger.

Behovet som beskrevet tar vi med når nytt tabellkomponent settes opp i nytt designsystem. Enn så lenge tenker jeg deres umiddelbare behov (både tydelig header og fjerne header på hver row) kan overstyres i deres løsning, i de kontekstene/sidene dere mener det trengs.
