### ISSUE TITLE
Replace @import with @use

### ISSUE THREAD

**Issue by maqnus** [folkehelseinstituttet/Fhi.Frontend.Style#40]
The Sass team discourages the continued use of the @import rule. Sass will gradually phase it out over the next few years, and eventually remove it from the language entirely. Prefer the @use rule instead. (Note that only Dart Sass currently supports @use. Users of other implementations must use the @import rule instead.)

https://sass-lang.com/documentation/at-rules/import

**Comment by proand** [comment]
I'll keep this open, but it's set on hold until next major rewrite of the package, eg. when we upgrade from Bootstrap 4 to Bootstrap 5, or some other change of that magnitude.

**Comment by yleaxeman** [comment]
This might be done a bit later. It was a bit more cumbersome to handle because of some issues regarding Angular. Also, Bootstrap 5.1.2 still use `@import`

**Comment by proand** [comment]
Closing this as stale...
