### ISSUE TITLE
Update some "basic"-CSS

### ISSUE THREAD

**Issue by proand** [folkehelseinstituttet/Fhi.Frontend.Style#67]
body text 19px all breakpoints
 lead 22px all breakpoints
 h5 22px all breakpoints

$fhi-blue-grey-1 -> #EDF4F7
$inline-link-color -> #075D8F
$inline-link-hover-color- #??????

**Comment by yleaxeman** [comment]
#64 tags along with this

**Comment by proand** [comment]
Waiting for speck for $inline-link-hover-color...
