### ISSUE TITLE
Generate icons list using the SVG's in icons folder

### ISSUE THREAD

**Issue by yleaxeman** [folkehelseinstituttet/Fhi.Frontend.Style#93]

**Comment by yleaxeman** [comment]
Trying https://github.com/MattDiMu/gulp-sassvg

**Comment by proand** [comment]
Maybe some tips here...?
https://webpack.js.org/guides/integrations/#gulp

**Comment by yleaxeman** [comment]
Suggested solution: running a custom node function without adding gulp or any other dependencies.
